const fs = require('fs');
const path = require('path');

function parseScript(filePath) {
    const content = fs.readFileSync(filePath, 'utf-8');
    const lines = content.split('\n');
    
    let description = "No description provided.";
    let usage = `node ${path.basename(filePath)}`;
    const args = [];

    for (const line of lines) {
        if (line.includes('@description')) {
            const parts = line.split('@description');
            if (parts[1]) description = parts[1].trim();
        }
        if (line.includes('@usage')) {
            const parts = line.split('@usage');
            if (parts[1]) usage = parts[1].trim();
        }
        if (line.includes('@arg')) {
            const parts = line.split('@arg');
            if (parts[1]) args.push(parts[1].trim());
        }
    }

    return {
        name: path.basename(filePath),
        description,
        usage,
        arguments: args
    };
}

function generateMarkdown(meta) {
    return `
# 📄 ${meta.name}

${meta.description}

## 🚀 Usage

\`\`\`bash
${meta.usage}
\`\`\`

${meta.arguments.length > 0 ? `## 🛠 Arguments\n\n${meta.arguments.map(arg => `- ${arg}`).join('\n')}` : ''}

---
*Generated by DocuMind*
`;
}

const targetFile = process.argv[2];
if (targetFile && fs.existsSync(targetFile)) {
    const metadata = parseScript(targetFile);
    const markdown = generateMarkdown(metadata);
    console.log(markdown);
} else {
    console.log("Usage: node index.js <script-file>");
}
